### ISSUE TITLE
Unable to map HMO data

### ISSUE THREAD

**Issue by julsraemy** [tgra/Linked-Art-Collection-Data-Workflow#1]
I wan't able to map `HumanMadeObject` data into the intermediate JSON. Here is the error I got: 

```
  File "/Users/julienraemy/Documents/GitHub/Linked-Art-Collection-Data-Workflow/map_data.py", line 78, in <module>
    map_data_func.save_file(json_data,b_mapped, record["id"])
  File "/Users/julienraemy/Documents/GitHub/Linked-Art-Collection-Data-Workflow/map_data_func.py", line 8, in save_file
    f = open(dir + "/"+ str(id) + ".json" , "w")
FileNotFoundError: [Errno 2] No such file or directory: 'humanmadeobject/data/b_mapped/12033.json'
```

**Comment by tgra** [comment]
This error is because either the directory path 'humanmadeobject/data/b_mapped/' does not exist, or else the file 12033.json file does not exist.

I have modified the save_file function mode so that it will create a file if it does not already exist. 

If there is still an error, check that the config variables are set correctly:

config["directory"]
config["b_mapped"]

the directory path for this code is composed as follows:

 config["directory"] + config["b_mapped"]

**Comment by julsraemy** [comment]
Thank you for your answer. After running: 

`python3 map_data.py --objtype humanmadeobject --config humanmadeobject/settings.yaml --template humanmadeobject/template.jsonnet`

I got the same error as previously. So I created a `b_mapped` directory, here is what I get: 

```
Traceback (most recent call last):
  File "/Users/julienraemy/Documents/GitHub/Linked-Art-Collection-Data-Workflow/map_data.py", line 45, in <module>
    data = json.load(json_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 352: invalid start byte
```
The config variables seem to be set correctly though.
